### PR TITLE
Convert to a pip package

### PR DESCRIPTION
**Pull request by Te-k**
Hey,

I have made some small modifications to have it as a pip package. What do you think?

The only problem I had is PEP8 recommend to avoid dash in package name, so the package is called `pythonmisp` (and not `python-misp`). If it is ok for you, it would make sense to rename the repo and title to have `pythonmisp` everywhere. If it works on your side, I can upload it to PyPI.

I am thinking about moving this [cli tool](https://github.com/Te-k/analyst-scripts/blob/master/misp/mispcli.py) to the package too, do you think it would be useful?

Sidenote: I am not familiar with all the setup.py options, feel free to update / add whatever is useful to you.

### CODE REVIEW

**Comment by nbareil** [comment]
Thanks for your contribution!

For the name, I would prefer the name `mispy`. Can I ask you to update your PR please?

**Comment by Te-k** [comment]
I just updated the code. What do you think of : 
* Uploading it on PyPi?
* Adding a CLI tool based on [mispcli](https://github.com/Te-k/analyst-scripts/blob/master/misp/mispcli.py) ?

**Comment by nbareil** [comment]
I am currently fighting with pypi but I will eventually upload it :)

I will keep you posted here.

**Comment by Te-k** [comment]
Cool, thanks !

**Comment by nbareil** [comment]
Done, here it is: https://pypi.python.org/pypi?:action=display&name=mispy&version=0.2

**Comment by Te-k** [comment]
:+1: 
Interested to add [mispcli](https://github.com/Te-k/analyst-scripts/blob/master/misp/mispcli.py) as a cli tool in the package?

**Pull request merged**
